### ISSUE TITLE
Practica #01, Análisis de 2 aplicaciones de Realidad Aumentada y Virtual.

### ISSUE THREAD

**Issue by ArteezyOne** [SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-ArteezyOne#2]
[Practica-01_Diego_García_Bautista.pdf](https://github.com/SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-ArteezyOne/files/6127527/Practica-01_Diego_Garcia_Bautista.pdf)

**Comment by Itzelzun** [comment]
Calif. 20

**Comment by Itzelzun** [comment]
calificacion 20

**Comment by josealfredo79** [comment]
Esta bien hecho y realizado
